### ISSUE TITLE
GroupController using HttpClient is missing

### ISSUE THREAD

**Issue by nguyentanphu** [AspNetCoreFromZeroToOverkill/WebFrontend#49]
I saw the GroupController using HttpClient in your video but it isn't in this source code. Can you update it please?

**Comment by joaofbantunes** [comment]
Like I mentioned in the YouTube comments, if you're looking at master or develop, it isn't there because it was removed in episode 29.
To see the code as it was when the video was recorded, you can use the tags.
In this case, the code that was being used in episode 24 was the same as in 21 -> https://github.com/AspNetCoreFromZeroToOverkill/WebFrontend/tree/episode021
